name: productivo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  percent_indicator: ^4.0.0
  date_picker_timeline: ^1.2.3
  syncfusion_flutter_datepicker: ^19.4.56
  syncfusion_flutter_charts: ^19.4.55
  html_editor_enhanced: ^2.4.0+1
  change_app_package_name: ^1.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  

  fonts:
     - family: 'bold'
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf     
     - family: 'medium'
       fonts:
         - asset: assets/fonts/Montserrat-Medium.ttf
     - family: 'regular'
       fonts:
         - asset: assets/fonts/Montserrat-Regular.ttf
     - family: 'semibold'
       fonts:
         - asset: assets/fonts/Montserrat-SemiBold.ttf
